<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Hs80.Audio</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hs80.Core\Hs80.Core.csproj" />
  </ItemGroup>

</Project>
