<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Hs80.App</RootNamespace>
    <AssemblyName>Hs80.App</AssemblyName>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hs80.Core\Hs80.Core.csproj" />
    <ProjectReference Include="..\Hs80.Audio\Hs80.Audio.csproj" />
    <ProjectReference Include="..\Hs80.Http\Hs80.Http.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HidSharp" Version="2.6.4" />
    <PackageReference Include="NAudio" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\*.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\*.mp3" />
    <Content Include="Assets\*.mp3">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
