<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Hs80.Http</RootNamespace>
    <AssemblyName>Hs80.Http</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Hs80.Core\Hs80.Core.csproj" />
  </ItemGroup>
</Project>
