namespace Hs80.Audio;

public static class PresetAudio
{
    public static IReadOnlyDictionary<string, string> Paths { get; } = new Dictionary<string, string>
    {
        ["LowBattery"] = "Assets/lb.mp3",
        ["Disconnect"] = "Assets/doff.mp3",
        ["Connect"] = "Assets/don.mp3",
        ["MicMute"] = "Assets/moff.mp3",
        ["MicUnmute"] = "Assets/mon.mp3",
        ["CH_Call_Ended"] = "Assets/CH_Call_Ended.mp3",
        ["CH_Call_Rejected"] = "Assets/CH_Call_Rejected.mp3",
        ["CH_Connected"] = "Assets/CH_Connected.mp3",
        ["CH_Disconnected"] = "Assets/CH_Disconnected.mp3",
        ["CH_Enter_Pairing_Mode"] = "Assets/CH_Enter_Pairing_Mode.mp3",
        ["CH_Incoming_Call"] = "Assets/CH_Incoming_Call.mp3",
        ["CH_Incoming_Call_Ended"] = "Assets/CH_Incoming_Call_Ended.mp3",
        ["CH_Low_Battery"] = "Assets/CH_Low_Battery.mp3",
        ["CH_Power_OFF"] = "Assets/CH_Power_OFF.mp3",
        ["CH_Power_ON"] = "Assets/CH_Power_ON.mp3",
        ["Doorbell"] = "Assets/Doorbell.mp3",
        ["Double"] = "Assets/Double.mp3",
        ["EN_Call_Ended"] = "Assets/EN_Call_Ended.mp3",
        ["EN_Call_Rejected"] = "Assets/EN_Call_Rejected.mp3",
        ["EN_Connected"] = "Assets/EN_Connected.mp3",
        ["EN_Disconnected"] = "Assets/EN_Disconnected.mp3",
        ["EN_Incoming_Call"] = "Assets/EN_Incoming_Call.mp3",
        ["EN_Incoming_Call_Ended"] = "Assets/EN_Incoming_Call_Ended.mp3",
        ["EN_Low_Battery"] = "Assets/EN_Low_Battery.mp3",
        ["EN_Pairing"] = "Assets/EN_Pairing.mp3",
        ["EN_Power_OFF"] = "Assets/EN_Power_OFF.mp3",
        ["EN_Power_ON"] = "Assets/EN_Power_ON.mp3",
        ["Failed"] = "Assets/Failed.mp3",
        ["Pressed"] = "Assets/Pressed.mp3",
        ["Successed"] = "Assets/Successed.mp3",
        ["Twc_Incoming_Call"] = "Assets/Twc_Incoming_Call.mp3",
        ["bton"] = "Assets/bton.mp3",
        ["doff"] = "Assets/doff.mp3",
        ["don"] = "Assets/don.mp3",
        ["eq"] = "Assets/eq.mp3",
        ["eq2"] = "Assets/eq2.mp3",
        ["eq3"] = "Assets/eq3.mp3",
        ["eq4"] = "Assets/eq4.mp3",
        ["hftd"] = "Assets/hftd.mp3",
        ["hftd_x2"] = "Assets/hftd_x2.mp3",
        ["lb"] = "Assets/lb.mp3",
        ["lftd"] = "Assets/lftd.mp3",
        ["mic_close_16kHz_16bit"] = "Assets/mic-close-16kHz-16bit.mp3",
        ["mic_open_16kHz_16bit"] = "Assets/mic-open-16kHz-16bit.mp3",
        ["moff"] = "Assets/moff.mp3",
        ["mon"] = "Assets/mon.mp3",
        ["not_connected_16k_16bit"] = "Assets/not-connected-16k-16bit.mp3",
        ["poff"] = "Assets/poff.mp3",
        ["pon"] = "Assets/pon.mp3",
        ["soff"] = "Assets/soff.mp3",
        ["son"] = "Assets/son.mp3",
    };
}
